services:
  traefik:
    labels:
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
    volumes:
      - type: bind
        source: ./docker/ssl.prod.yaml
        target: /etc/traefik/ssl.yml
